version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: wash_db
    container_name: postgre_db
    restart: always



