# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.6
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6
    - name: Build with Maven
      env:
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      run: mvn -B package --file server/pom.xml
